edition = 1
exports = ["askaway-proto/ask-service/ask.proto"]

[package]
name = "ask-service-test"
description = "Ask service actor"

[package.actr_type]
manufacturer = "askaway1"
name = "AskService"

[system.signaling]
url = "wss://actrix1.develenv.com/signaling/ws"

[system.deployment]
realm_id = 2368_266_035

[system.discovery]
visible = true

[system.webrtc]
force_relay = false
stun_urls = ["stun:actrix1.develenv.com:3478"]
turn_urls = ["turn:actrix1.develenv.com:3478"]

[acl]

[[acl.rules]]
permission = "allow"
types = ["askaway1+Client", "acmeopenclaw+AskawayClient"]
